FROM jenkins/jenkins:lts

USER root

#Install wget
RUN apt-get update && apt-get install -y wget

# Install dotnet 8
RUN wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y dotnet-sdk-8.0

USER jenkins

# RUN jenkins-plugin-cli --plugins \
# git \
# docker \
# paginate-builds